version: 2.1

orbs:
  architect: giantswarm/architect@5.4.0

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/
          image: giantswarm/guestfs
