version: 2.1

orbs:
  architect: giantswarm/architect@5.10.1

workflows:
  build:
    jobs:
    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        image: giantswarm/guestfs
